spring:
  application:
    name: SpringDataProjectMapper

  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jackson:
    locale: ru_RU
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    default-schema: public

server:
  port: 8082

schema:
  path: classpath:schema.json